//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityOrnek.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblNotlar
    {
        public int NotID { get; set; }
        public Nullable<int> OGR { get; set; }
        public Nullable<int> Ders { get; set; }
        public Nullable<short> Vize { get; set; }
        public Nullable<short> Final { get; set; }
        public Nullable<short> But { get; set; }
        public Nullable<decimal> Ortalama { get; set; }
        public Nullable<bool> Durum { get; set; }
    }
}
